beds/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<str:hospital_id>/create', views.BedsCreate.as_view(), name='beds-create'),
    path('<str:pk>/update', views.BedsUpdate.as_view(), name='beds-update'),
    path('<str:pk>/delete', views.BedsDelete.as_view(), name='beds-delete'),
    path('<str:hospital_id>/<str:action>', views.BedsList.as_view(), name='beds-list-action'),
    path('<str:hospital_id>', views.BedsList.as_view(), name='beds-list'),
]

szezlong/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from hospitals.views import HospitalList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hospital/', include('hospitals.urls')),
    path('beds/', include('beds.urls')),
    path('tickets/', include('tickets.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', HospitalList.as_view())
]

# Serve static and media files from development server
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tickets/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<str:bed_id>/create', views.TicketsCreate.as_view(), name='ticket-create-bed'),
    path('<str:hospital_id>/<str:action>/create', views.TicketsCreate.as_view(), name='ticket-create'),
    path('<str:pk>/update', views.TicketsUpdate.as_view(), name='ticket-update'),
    path('<str:pk>/delete', views.TicketsCreate.as_view(), name='ticket-delete'),
    path('<str:mode>', views.TicketsList.as_view(), name='ticket-list-all'),
    path('<str:hospital_id>/<str:mode>', views.TicketsList.as_view(), name='ticket-list'),
    path('<str:hospital_id>', views.TicketsList.as_view(), name='ticket-list-default'),
    path('', views.hospitals_list, name='ticket-hospitals-list'),
]

tickets/models.py
from datetime import timedelta, datetime

from django.utils.translation import gettext_lazy as _
from django.db import models
from django.db.models import Q

from django_extensions.db.fields import CreationDateTimeField
from django_extensions.db.fields import ModificationDateTimeField
from beret_utils.random_code import Codes
from common import ChroniclerModel

from hospitals.models import Hospital, Specialisation
from beds.models import Bed


def default_expiration_date():
    return datetime.now() + timedelta(hours=6)


class Ticket(models.Model):
    class Meta:
        ordering = ["number"]
    
    FIELDS = [
        "code",
        "description",
        "hospital",
        "bed",
        "respirator",
        "oxygen",
        "child",
        "use_respirator",
        "use_oxygen",
        "expiration_date",
        "canceled",
        "canceled_reason",
        "created_on",
        "last_modified_on",
        "prev"
    ]

    code = models.CharField(_("Kod Biletu"), max_length=16, primary_key=True, blank=True)
    number = models.CharField(_("Numer Pacjenta"), max_length=128, db_index=True, blank=True)
    hospital = models.ForeignKey(Hospital, verbose_name=_("Szpital"), on_delete=models.CASCADE)
    bed = models.OneToOneField(Bed, verbose_name=_("Łóżko"), on_delete=models.SET_NULL, null=True, blank=True)
    respirator = models.BooleanField(_("Potrzebny Respirator"), default=False)
    oxygen = models.BooleanField(_("Potrzebny Tlen"), default=False)
    child = models.BooleanField(_("Potrzebne Łóżko Dziecięce"), default=False)
    use_respirator = models.BooleanField(_("Użyty Mobilny Respirator"), default=False)
    use_oxygen = models.BooleanField(_("Użyty Mobilny Tlen"), default=False)
    sat_begin = models.FloatField(_("Saturacja początkowa"), default=100)
    sat_end = models.FloatField(_("Saturacja końcowa"), default=100)
    expiration_date = models.DateTimeField(
        _("Data Ważności"),
        null=True,
        blank=True,
        editable=False,
        default=default_expiration_date
    )
    canceled = models.BooleanField(_("Anulowane"), default=False, editable=False)
    canceled_reason = models.TextField(_("Przyczyna Anulowania"), null=True, blank=True, editable=False)
    created_on = CreationDateTimeField()
    last_modified_on = ModificationDateTimeField()
    prev = models.ForeignKey("DeletedTicket", null=True, editable=False, on_delete=models.CASCADE)

    @property
    def to_dict(self) -> dict:
        ticket_dict = {}
        for field in self.FIELDS:
            ticket_dict[field] = getattr(self, field, None)
        return ticket_dict

    def __str__(self):
        return f"{self.code} expire {self.expiration_date.strftime('%d %h %Y %H:%M')}"

    def gen_code(self):
        code_generator = Codes(
            chars=Codes.DEFAULT_CHARS.upper(),
            count=Ticket.objects.count() + DeletedTicket.objects.count() + 1
        )
        while True:
            code = f"{self.hospital.code}:{code_generator()}"
            if not Ticket.objects.filter(code=code).count() and not DeletedTicket.objects.filter(code=code).count():
                return code

    @property
    def is_expired(self):
        return self.expiration_date <= datetime.now()

    @classmethod
    def expires(cls, queryset=None):
        if queryset is None:
            queryset = cls.objects
        return queryset.filter(expiration_date__lte=datetime.now())

    @classmethod
    def attentions(cls, queryset=None):
        queryset = cls.expires(queryset)\
            .filter(Q(oxygen=True) & Q(use_oxygen=False) & Q(bed__oxygen=False))\
            .filter(Q(respirator=True) & Q(use_respirator=False) & Q(bed__respirator=False))\
            .filter(Q(oxygen=False) & Q(use_oxygen=True) | Q(bed__oxygen=True))\
            .filter(Q(respirator=True) & Q(use_respirator=False) & Q(bed__respirator=False))
        return queryset

    @property
    def attention(self):
        reasons = {
            _("Przeterminowany"): self.is_expired,
            _("Brak Łóżka"): self.bed is None
        }
        if self.bed:
            reasons.update({
                _("Nie Ma Tlenu"): self.oxygen and not (self.use_oxygen or self.bed.oxygen),
                _("Nie Ma Respiratora"): self.respirator and not (self.use_respirator or self.bed.respirator),
                _("Blokuje Tlen"): not self.oxygen and (self.use_oxygen or self.bed.oxygen),
                _("Blokuje Respirator"): not self.respirator and (self.use_respirator or self.bed.respirator),
            })

        # if not any(reasons.values()):
        #     return None
        return [text for text, show in reasons.items() if show]

    def save(self, *args, **kwargs):
        if self.code:
            self.archive()
            self.prev_id = self.code

        self.code = self.gen_code()
        return super().save(*args, **kwargs)

    def archive(self, reason="ticket change"):
        delete_ticket = DeletedTicket(**self.to_dict)
        delete_ticket.delete_reason = reason
        delete_ticket.save()
        self.delete(keep_parents=True)


class DeletedTicket(models.Model):
    delete_on = CreationDateTimeField(editable=False)
    delete_reason = models.CharField(_("Przyczyna skasowania"), max_length=1024, null=False, blank=False)
    code = models.CharField(_("Kod Biletu"), max_length=16, primary_key=True)
    description = models.CharField(_("Opis"), max_length=128, db_index=True, blank=True, null=True)
    hospital = models.ForeignKey(Hospital, verbose_name=_("Szpital"), on_delete=models.CASCADE)
    bed = models.ForeignKey(Bed, verbose_name=_("Łóżko"), on_delete=models.CASCADE, null=True)
    respirator = models.BooleanField(_("Potrzebny Respirator"))
    oxygen = models.BooleanField(_("Potrzebny Tlen"))
    child = models.BooleanField(_("Potrzebne Łóżko Dziecięce"))
    use_respirator = models.BooleanField(_("Użyty Mobilny Respirator"))
    use_oxygen = models.BooleanField(_("Użyty Mobilny Tlen"))
    expiration_date = models.DateTimeField(_("Data Ważności"), null=True, blank=True)
    canceled = models.BooleanField(_("Anulowane"))
    canceled_reason = models.TextField(_("Przyczyna Anulowania"), null=True, blank=True)
    created_on = models.DateTimeField()
    last_modified_on = models.DateTimeField()
    prev = models.ForeignKey("DeletedTicket", null=True, editable=False, on_delete=models.CASCADE)

tickets/forms.py
from django.forms import ModelForm
from django.forms import fields
from django.utils.translation import gettext_lazy as _

from .models import Ticket


class TicketForm(ModelForm):
    class Meta:
        model = Ticket
        fields = "__all__"


class CreateTicketForm(ModelForm):
    class Meta:
        model = Ticket
        fields = ["number", "sat_begin", "sat_end", "respirator", "oxygen", "child", "hospital"]

    def save(self, commit=True):
        hospital = self.cleaned_data["hospital"]
        child = self.cleaned_data["child"]
        respirator = self.cleaned_data["respirator"]
        oxygen = self.cleaned_data["oxygen"]
        beds = hospital.bed_set.filter(child=child, oxygen=oxygen, respirator=respirator)
        if beds.count():
            obj = super().save(commit=False)
            obj.bed = beds[0]
            obj.save()
            return obj

tickets/views.py
from typing import Optional

from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import UpdateView

from .forms import TicketForm, CreateTicketForm
from .models import Bed
from .models import Hospital
from .models import Ticket


from django.core.exceptions import PermissionDenied
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render

from config import attentions, expires


def hospitals_list(request: HttpRequest) -> HttpResponse:
    template_name = 'tickets/hospitals_list.html'
    context = {
        "hospitals": Hospital.objects.all(),
    }

    return render(
        request,
        template_name,
        context
    )


class TicketsList(ListView):
    model = Ticket
    template_name = 'tickets/list_hospital.html'
    context_object_name = 'tickets'
    mode = None
    hospital = None

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        hospital_id = self.kwargs.get("hospital_id")
        self.mode = self.kwargs.get("mode", "orphans")
        if hospital_id is not None:
            self.hospital = Hospital.objects.get(pk=hospital_id)
            queryset = queryset.filter(hospital_id=hospital_id)
        if self.mode == "orphans":
            queryset = queryset.filter(bed=None)
        elif self.mode == "expires":
            queryset = expires(queryset)
        elif self.mode == "attentions":
            queryset = attentions(queryset)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["hospital"] = self.hospital
        context["mode"] = self.mode
        return context


class TicketsCreate(CreateView):
    model = Ticket
    template_name = 'tickets/create.html'
    form_class = TicketForm
    context_object_name = 'ticket'
    beds = None

    def get_success_url(self):
        return reverse_lazy('hospital-list')

    def get_form(self, form_class=None):
        """Return an instance of the form to be used in this view."""
        if form_class is None:
            form_class = self.form_class

        kwargs = self.get_form_kwargs() or {}
        initial = kwargs.get("initial", {})

        bed_id = self.kwargs.get("bed_id")
        if bed_id:
            self.bed = Bed.objects.get(pk=bed_id)
            initial['bed'] = self.bed
            self.hospital = self.bed.hospital
            self.beds = Bed.objects.filter(pk=bed_id)
        else:
            initial["bed"] = None
            hospital_id = self.kwargs.get("hospital_id")
            self.hospital = Hospital.objects.get(pk=hospital_id)
            self.action = self.kwargs.get("action")
            self.beds = Bed.objects.filter(hospital=self.hospital)

        initial['hospital'] = self.hospital
        param = self.action

        if param is not None:
            if param == "all":
                initial.update({
                    "respirator": False,
                    "oxygen":     False
                })
                self.beds = self.beds.filter(ticket__isnull=True, child=False, respirator=False, oxygen=False)
            elif param == "respirators":
                initial.update({
                    "respirator": True,
                    "oxygen":     True
                })
                self.beds = self.beds.filter(ticket__isnull=True, child=False)
                if self.hospital.respirators <= self.hospital.ticket_set.filter(use_respirator=True).count():
                    self.beds = self.beds.filter(respirator=True)
            elif param == "oxygen":
                initial.update({
                    "respirator": False,
                    "oxygen":     True
                })
                self.beds = self.beds.filter(ticket__isnull=True, child=False)
                if self.hospital.oxygens <= self.hospital.ticket_set.filter(use_oxygen=True).count():
                    self.beds = self.beds.filter(respirator=False, oxygen=True)
            elif param == "children":
                initial.update({
                    "respirator": False,
                    "oxygen":     False,
                    "child":      True
                })
                self.beds = self.beds.filter(ticket__isnull=True, child=True, respirator=False, oxygen=False)
            elif param == "respirators-children":
                initial.update({
                    "respirator": False,
                    "oxygen":     False,
                    "child":      True
                })
                self.beds = self.beds.filter(ticket__isnull=True, child=True)
                if self.hospital.respirators <= self.hospital.ticket_set.filter(use_respirator=True).count():
                    self.beds = self.beds.filter(respirator=True)
            elif param == "oxygen-children":
                initial.update({
                    "respirator": False,
                    "oxygen":     False,
                    "child":      True
                })
                self.beds = self.beds.filter(ticket__isnull=True, child=True)
                if self.hospital.oxygens <= self.hospital.ticket_set.filter(use_oxygen=True).count():
                    self.beds = self.beds.filter(respirator=False, oxygen=True)

        kwargs["initial"] = initial
        form = form_class(**kwargs)

        # if self.beds.count() > 0:
        #     form.fields["bed"].queryset = self.beds
        # else:
        #     form.fields["bed"].widget.attrs["readonly"] = True
        #
        # form.fields["hospital"].widget.attrs["readonly"] = True

        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_beds"] = self.beds.count() > 0
        return context


class TicketsUpdate(UpdateView):
    model = Ticket
    template_name = 'tickets/update.html'
    form_class = TicketForm
    fields = '__all__'
    context_object_name = 'Ticket'
    beds = None

    def get_form(self, form_class=None):
        """Return an instance of the form to be used in this view."""
        if form_class is None:
            form_class = self.form_class

        kwargs = self.get_form_kwargs()

        obj = self.get_object()

        self.beds = obj.hospital.bed_set

        self.beds = self.beds.filter(ticket__isnull=True, respirator=False, oxygen=False)

        if obj.respirator:
            if obj.hospital.respirators <= obj.hospital.ticket_set.filter(use_respirator=True).count():
                self.beds = self.beds.filter(respirator=True)
        elif not obj.respirator and obj.oxygen:
            if obj.hospital.oxygens <= obj.hospital.ticket_set.filter(use_oxygen=True).count():
                self.beds = self.beds.filter(respirator=False, oxygen=True)

        if obj.child:
            self.beds = self.beds.filter(child=True)
        else:
            self.beds = self.beds.filter(child=False)

        form = form_class(**kwargs)

        if self.beds.count() > 0:
            form.fields["bed"].queryset = self.beds
        else:
            form.fields["bed"].widget.attrs["readonly"] = True

        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_beds"] = self.beds.count() > 0
        return context

    def get_success_url(self):
        return reverse_lazy('ticket-list', kwargs={
            'hospital_id': self.object.hospital.pk,
            'mode':        "orphans"
        })


class TicketsDelete(DeleteView):
    model = Ticket
    template_name = 'tickets/delete.html'

    def get_success_url(self):
        return reverse_lazy('ticket-list', kwargs={
            'hospital_id': self.object.hospital.pk,
            'mode':        "orphans"
        })

tickets/templates/tickets/create.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}


{% translate "Wprowadź Nowego Pacjenta." as title %}
{% block container %}
<div class="container-fluid">
        <div class="row">

            <div width="100%" style="min-width: 400px; margin: 0 auto; margin-top: 20px; border: 3px red solid; padding: 20px; border-radius: 20px; margin-bottom: 18px; background-color: white;">

                <hr>
                    <h3 class="text-center">
                        Szpital Bielański
                    </h3>
                <hr>
                <form role="form" class="form"method="post">
                    {% csrf_token %}
{#                    <input#}
{#                            type="hidden"#}
{#                            readonly=""#}
{#                            class="select"#}
{#                            required=""#}
{#                            id="id_hospital"#}
{#                            value="{{ fields.hospital.value }}"#}
{#                    />#}
                    <div class="form-group">
                        <label for="exampleInput">
                            Numer dokumentu:
                        </label>
                        <input
                                type="text"
                                name="number"
                                maxlength="128"
                                class="textinput textInput form-control"
                                id="id_number"
                                style="border-radius: 20px; border: 2px #5bc0de solid; max-width:400px; height: 40px;"
                        />
                    </div>
                    <div class="form-group">

                        <label for="exampleInput">
                            Saturacja przed:
                        </label>
                        <input type="number" name="sat_begin" step="any" class="form-control" required=""
                               id="id_sat_begin" style="border-radius: 20px;
                        border: 2px #5bc0de solid; max-width:400px; height: 40px;"/>
                    </div>
                    <div class="form-group">

                        <label for="exampleInput2">
                            Saturacja po:
                        </label>
                        <input
                            type="number"
                            name="sat_end"
                            step="any"
                            class="form-control"
                            required=""
                            id="id_sat_end"
                            style="border-radius: 20px; border: 2px #5bc0de solid; max-width:400px; height: 40px;"
                        />
                    </div>
                    <hr>

                    <center>
                        <button style="border-radius: 20px; border: 2px #5bc0de solid; background: white !important; color: black;" class="btn btn-outline-success my-2 my-sm-0" data-toggle="tooltip" data-placement="bottom" title="Respirator"><i style="color: black;" class="fas fa-2x fa-lungs"></i></button>&nbsp;&nbsp;&nbsp;
                        <button style="border-radius: 20px; border: 2px #5bc0de solid; background: white !important; color: black;" class="btn btn-outline-success my-2 my-sm-0" data-toggle="tooltip" data-placement="bottom" title="Tlen"><i style="color: black;" class="fas fa-2x fa-wind"></i></button>&nbsp;&nbsp;&nbsp;
                        <button style="border-radius: 20px; border: 2px #5bc0de solid; background: white !important; color: black;" class="btn btn-outline-success my-2 my-sm-0" data-toggle="tooltip" data-placement="bottom" title="Dla dzieci"><i style="color: black;" class="fas fa-2x fa-baby"></i></button>
                    </center>

                    <hr>
{#                    <h5 class="text-center">#}
{#                        Kod biletu: <b>123456789</b>#}
{#                    </h5>#}
{#                    <h5 class="text-center">#}
{#                        Numer łóżka: <b>123</b>#}
{#                    </h5>#}
                    <h5 class="text-center">
                        ID operatora: <b>789</b>
                    </h5>

                    <hr>

                    <button type="submit" class="btn btn-primary" style="border-radius: 20px; border: 2px #ff0000 solid; background: white !important; color: black;">
                        <i style="color: black;" class="fas fa-times"></i>&nbsp; <b>Anuluj</b>
                    </button>

                    <button type="submit" style="float: right; border-radius: 20px; border: 2px #5bc0de solid; background: white !important; color: black;" class="btn btn-primary">
                       <i style="color: black;" class="fas fa-save"></i>&nbsp; <b>Przypisz</b>
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock container %}

tickets/templates/tickets/create_org.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}


{% translate "Wprowadź Nowego Pacjenta." as title %}
{% block container %}
    <div class="card" style="margin: 0 auto; margin-top: 20px; border: 3px red solid; padding: 20px; border-radius:
    20px; margin-bottom: 18px; background-color: white;">

            <h5 class="card-title"><center>{% translate "Utwórz nowego pacjenta" %}</center></h5>

        <div class="card card-body" style="padding: 10px; border-radius: 20px;">
        <form class="form-inline my-2 center" method="post" style="display: flex; align-items: center">
                {% csrf_token %}
                {{ form|crispy }}
                <button
                        type="submit"
                        class="btn btn-success"
                        name="button"
                        value="create_1"
                >
                    {% translate "Stwórz" %}
                </button>
                <button
                        type="submit"
                        class="btn btn-success"
                        name="button"
                        value="create_2"
                >
                    {% translate "Stwórz" %}
                </button>
            </form>
        </div>
    </div>
{% endblock container %}

tickets/templates/tickets/delete.html
{% extends "base.html" %}
{% load i18n %}


{% translate "Delete Bed" as title %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">{% translate "Delete Bed" %} {{object}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                {% translate "Are you sure you want to delete" %} <strong>{{ object }}</strong> ?
            </div>
            <button type="submit" class="btn btn-danger">{% translate "Delete" %}</button>
        </form>
    </div>
</div>
{% endblock container %}

tickets/templates/tickets/hospitals_list.html
{% extends "base.html" %}
{% load i18n %}

{% translate "Hospitals List" as title %}
{% get_current_language as LANGUAGE_CODE %}
{% block extra_js %}
{% endblock extra_js %}
{% block container %}
    <ul class="nav flex-column">
        {% for hospital in hospitals %}
            <li class="nav-item">
                <a
                        class="nav-link"
                        href="{% url 'ticket-list' hospital.pk "orphans" %}"
                >
                    {{ hospital }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock container %}

tickets/templates/tickets/list.html
{% extends "base.html" %}
{% load i18n %}

{% translate "Lista Zleceń na Łóżka" as title %}
{% block container %}
    <h2><center>{{ hospital.code }} {{ hospital.name }}</center></h2>
    <h3><center>{{ hospital.address }}</center></h3>
<br>
    <ul class="nav nav-tabs justify-content-center">
        <li class="nav-item">
            <a
                    {% if mode == "all" %}
                        class="nav-link active" aria-current="page"
                    {% else %}
                        class="nav-link"
                    {% endif %}
                        href="{% url 'ticket-list' hospital.pk "all" %}"
            >
                <i style="color: black;" class="fas fa-infinity"></i>&nbsp;
                {% translate "Wszystkie Zlecenia" %}
            </a>
        </li>
        <li class="nav-item">
            <a
                    {% if mode == "orphans" %}
                        class="nav-link active" aria-current="page"
                    {% else %}
                        class="nav-link"
                    {% endif %}
                        href="{% url 'ticket-list' hospital.pk "orphans" %}"
            >
                <i style="color: black;" class="fas fa-hourglass-start"></i>&nbsp;
                {% translate "Oczekujące Zlecenia" %}
            </a>
        </li>
        <li class="nav-item">
            <a
                    {% if mode == "expires" %}
                        class="nav-link active" aria-current="page"
                    {% else %}
                        class="nav-link"
                    {% endif %}
                        href="{% url 'ticket-list' hospital.pk "expires" %}"
            >
                <i style="color: black;" class="fas fa-hourglass-end"></i>&nbsp;
                {% translate "Przeterminowane Zlecenia" %}
            </a>
        </li>
        <li class="nav-item">
            <a
                    {% if mode == "attentions" %}
                        class="nav-link active" aria-current="page"
                    {% else %}
                        class="nav-link"
                    {% endif %}
                        href="{% url 'ticket-list' hospital.pk "attentions" %}"
            >
                <i style="color: black;" class="fas fa-exclamation"></i>&nbsp;
                {% translate "Zlecenia z Uwagami" %}
            </a>
        </li>
    </ul>

    <div class="card-group hospital-cards">
        {% for ticket in tickets %}
            <div class="card" style="width: 18rem;">
                <div class="card-body" style="margin: 10px;">
                <h5 class="card-title" style="font-size: 15px; margin-top: 7px;"><center><b>{{ ticket }}</b></center></h5>
                <hr>
                {% if ticket.bed %}
                        <h6 class="card-subtitle">{{ ticket.bed }}</h6>
                        {% if ticket.bed.description %}
                            <p class="card-text">{{ ticket.bed.description }}</p>
                        {% endif %}
                        {% if ticket.bed.respirator %}
                            <h6 class="card-subtitle" style="margin-top: 3px;">{% translate "Respirator" %}</h6>
                        {% endif %}
                        {% if ticket.bed.oxygen %}
                            <h6 class="card-subtitle" style="margin-top: 3px;">{% translate "Tlen" %}</h6>
                        {% endif %}
                        {% if ticket.bed.child %}
                            <h6 class="card-subtitle" style="margin-top: 3px;">{% translate "Dzięcięce" %}</h6>
                        {% endif %}

                    {% endif %}

                    {% for message in bed.ticket.attention %}
                        <h6 class="card-subtitle">{{ message }}</h6>
                    {% endfor %}
                    <br>
                    <a
                            href="{% url 'ticket-update' ticket.pk %}"
                            class="card-link"
                    >
                        <i style="color: black;" class="fas fa-check"></i>&nbsp;
                        {% translate "Aktualizuj Dane Pacjenta" %}
                    </a><br>
                    <a
                            href="{% url 'ticket-delete' ticket.pk %}"
                            class="card-link"
                    >
                        <i style="color: black;" class="fas fa-times"></i>&nbsp;
                        {% translate "Zamknij Przydział Pacjenta" %}
                    </a>
                </div>
            </div>
        {% endfor %}
        <a href="{% url 'beds-create' hospital.pk %}" class="card-link">
            {% translate "Wprowadź Nowe Łóżka." %}
        </a>

    </div>

{% endblock container %}

tickets/templates/tickets/update.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% translate "Aktualizuj Pacjenta" as title %}
{% block container %}
    <div class="card" style="margin: 0 auto; margin-top: 20px; border: 3px red solid; padding: 20px; border-radius:
    20px; margin-bottom: 18px; background-color: white;">
        <div class="card-header" style="padding: 10px; border-top-left-radius: 20px; border-top-right-radius:
        20px;">
            <h5 class="card-title">{% translate "Aktualizuj Pacjenta" %}</h5>
        </div>
        <div class="card card-body" style="padding: 10px; border-bottom-left-radius: 20px; border-bottom-right-radius:
        20px;">
            <form class="form-inline my-2 center" method="post" style="display: flex; align-items: center">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">{% translate "Uaktualnij" %}</button>
            </form>
        </div>
    </div>
{% endblock container %}